# Site settings
title: "sure's portfolio"
description: "Xuan Li's resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Xuan Li"
resume_title:                   "Backend developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "xluow5965@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "0493303989"
resume_contact_address:         "Sydney, NSW 2000"

resume_header_contact_info:     "Sydney, NSW 2000 • 0493303989 • xluow5965@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am currently doing my master’s in computer science at the University of Wollongong, 
 I am an AI-driven software development and data analytics enthusiast.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sure6"
  resume_twitter_url:           "https://twitter.com/leesure16"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/leesure125"
  resume_linkedin_url:          "https://www.linkedin.com/in/xuan-li-21a42b217/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
  resume_csdn_url:            "https://blog.csdn.net/qq_40229790?spm=1011.2124.3001.5343"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
